// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: LexicoS2H.flex
package JFlex;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class LexicoS2H {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\2\2\1\3\22\0\1\4\1\5\1\6"+
    "\1\7\2\0\1\10\1\0\1\11\1\12\1\13\1\14"+
    "\1\15\1\14\1\16\1\17\2\20\1\21\1\22\2\23"+
    "\4\24\1\25\1\15\1\26\1\27\1\26\1\15\1\0"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\50"+
    "\1\57\1\50\1\60\1\0\1\61\1\0\1\62\1\0"+
    "\32\50\1\63\1\64\1\65\7\0\1\2\u01a2\0\2\2"+
    "\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\1\1\5\1\1"+
    "\1\6\1\7\1\10\1\5\1\10\3\11\1\12\1\13"+
    "\23\14\1\15\1\16\1\17\1\1\1\20\1\12\1\0"+
    "\1\21\1\0\1\4\1\22\1\0\1\23\1\0\1\11"+
    "\1\24\1\14\1\25\32\14\4\0\2\23\2\0\1\11"+
    "\1\0\1\24\5\14\1\25\5\14\1\25\7\14\1\26"+
    "\2\0\1\23\2\0\1\22\1\0\2\14\1\0\7\14"+
    "\2\23\2\0\2\27\1\0\2\30\2\0\3\14\1\0"+
    "\1\26\3\0\1\25";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\66\0\154\0\66\0\242\0\330\0\66"+
    "\0\u010e\0\66\0\66\0\66\0\u0144\0\u017a\0\u01b0\0\u01e6"+
    "\0\u021c\0\242\0\242\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a"+
    "\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da"+
    "\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e\0\66\0\66"+
    "\0\66\0\u0654\0\66\0\66\0\330\0\330\0\u068a\0\66"+
    "\0\u06c0\0\u06f6\0\u072c\0\u0144\0\u0762\0\u0798\0\u07ce\0\u03cc"+
    "\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948\0\u097e"+
    "\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e"+
    "\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde"+
    "\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec\0\u0e22\0\66\0\u0e58"+
    "\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\u0f66\0\u0f9c\0\u0fd2\0\u1008"+
    "\0\u103e\0\u1074\0\u10aa\0\u10e0\0\u1116\0\u114c\0\u1182\0\u11b8"+
    "\0\u11ee\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12fc\0\u1332\0\u1368"+
    "\0\u0d80\0\u139e\0\u13d4\0\u0db6\0\u140a\0\u1440\0\u1476\0\u14ac"+
    "\0\u14e2\0\u1518\0\u154e\0\u1584\0\u15ba\0\u15f0\0\u1626\0\u165c"+
    "\0\u1692\0\u16c8\0\u03cc\0\u140a\0\u16fe\0\u1734\0\u1440\0\u0e8e"+
    "\0\u176a\0\u1440\0\u0e8e\0\u17a0\0\u17d6\0\u180c\0\u1842\0\u1878"+
    "\0\u18ae\0\u176a\0\u18e4\0\u191a\0\u1950\0\66";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\2\14\1\10\1\15\1\16\1\17"+
    "\1\20\3\21\1\10\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\33"+
    "\1\36\1\37\1\40\1\41\1\42\2\33\1\43\1\44"+
    "\2\33\1\45\1\46\1\47\1\50\1\10\1\51\1\52"+
    "\1\53\67\0\1\3\113\0\1\54\36\0\6\55\1\56"+
    "\4\55\1\57\52\55\10\0\1\60\75\0\5\61\50\0"+
    "\1\62\7\0\1\63\64\0\1\64\1\0\5\65\3\0"+
    "\30\66\24\0\1\64\1\0\3\65\2\21\3\0\30\66"+
    "\24\0\1\64\1\0\5\21\3\0\30\66\26\0\5\33"+
    "\3\0\10\33\1\67\12\33\1\70\4\33\26\0\5\33"+
    "\3\0\4\33\1\71\11\33\1\72\2\33\1\73\6\33"+
    "\26\0\5\33\3\0\13\33\1\74\14\33\26\0\5\33"+
    "\3\0\4\33\1\75\3\33\1\76\17\33\26\0\5\33"+
    "\3\0\15\33\1\77\12\33\26\0\5\33\3\0\1\100"+
    "\12\33\1\101\14\33\26\0\5\33\3\0\1\102\27\33"+
    "\26\0\5\33\3\0\30\33\26\0\5\33\3\0\15\33"+
    "\1\103\4\33\1\70\5\33\26\0\5\33\3\0\16\33"+
    "\1\104\11\33\26\0\5\33\3\0\10\33\1\105\17\33"+
    "\26\0\5\33\3\0\16\33\1\106\11\33\26\0\5\33"+
    "\3\0\16\33\1\107\11\33\26\0\5\33\3\0\5\33"+
    "\1\110\7\33\1\70\1\33\1\111\10\33\26\0\5\33"+
    "\3\0\1\112\27\33\26\0\5\33\3\0\2\33\1\113"+
    "\1\33\1\114\21\33\1\115\1\33\26\0\5\33\3\0"+
    "\4\33\1\116\3\33\1\117\5\33\1\70\2\33\1\120"+
    "\6\33\26\0\5\33\3\0\7\33\1\121\20\33\26\0"+
    "\5\33\3\0\4\33\1\122\23\33\72\0\1\60\1\0"+
    "\13\55\1\57\3\55\1\0\46\55\16\0\1\123\1\0"+
    "\5\61\41\0\7\124\1\125\3\124\1\126\52\124\1\63"+
    "\1\127\1\63\1\130\62\63\1\131\3\0\12\131\1\132"+
    "\1\131\5\133\1\134\2\131\30\135\6\131\20\0\5\66"+
    "\3\0\30\66\26\0\5\33\3\0\21\33\1\70\6\33"+
    "\26\0\5\33\3\0\6\33\1\136\21\33\26\0\5\33"+
    "\3\0\16\33\1\137\11\33\26\0\5\33\3\0\4\33"+
    "\1\140\23\33\26\0\5\33\3\0\16\33\1\141\11\33"+
    "\26\0\5\33\3\0\2\33\1\70\2\33\1\70\22\33"+
    "\26\0\5\33\3\0\22\33\1\142\5\33\26\0\5\33"+
    "\3\0\3\33\1\143\24\33\26\0\5\33\3\0\13\33"+
    "\1\144\14\33\26\0\5\33\3\0\16\33\1\145\11\33"+
    "\26\0\5\33\3\0\23\33\1\146\4\33\26\0\5\33"+
    "\3\0\2\33\1\70\20\33\1\70\4\33\26\0\5\33"+
    "\3\0\10\33\1\147\17\33\26\0\5\33\3\0\6\33"+
    "\1\150\21\33\26\0\5\33\3\0\3\33\1\146\24\33"+
    "\26\0\5\33\3\0\23\33\1\151\4\33\26\0\5\33"+
    "\3\0\5\33\1\70\22\33\26\0\5\33\3\0\4\33"+
    "\1\147\23\33\26\0\5\33\3\0\21\33\1\152\6\33"+
    "\26\0\5\33\3\0\7\33\1\153\20\33\26\0\5\33"+
    "\3\0\13\33\1\70\1\33\1\154\12\33\26\0\5\33"+
    "\3\0\10\33\1\155\17\33\26\0\5\33\3\0\14\33"+
    "\1\156\13\33\26\0\5\33\3\0\14\33\1\146\13\33"+
    "\26\0\5\33\3\0\24\33\1\157\3\33\26\0\5\33"+
    "\3\0\4\33\1\147\3\33\1\160\17\33\26\0\5\33"+
    "\3\0\22\33\1\70\5\33\24\0\1\123\1\0\5\161"+
    "\41\0\7\124\1\162\3\124\1\163\61\124\1\162\3\124"+
    "\1\163\3\124\1\164\46\124\13\165\1\126\3\165\1\0"+
    "\46\165\1\0\1\127\64\0\1\131\3\0\14\131\4\166"+
    "\43\131\3\0\14\131\5\167\42\131\3\0\12\131\1\132"+
    "\1\131\5\133\3\131\30\135\7\131\3\0\14\131\4\170"+
    "\43\131\3\0\14\131\5\135\3\131\30\135\6\131\20\0"+
    "\5\33\3\0\10\33\1\171\17\33\26\0\5\33\3\0"+
    "\13\33\1\70\14\33\26\0\5\33\3\0\1\172\27\33"+
    "\26\0\5\33\3\0\2\33\1\172\25\33\26\0\5\33"+
    "\3\0\11\33\1\35\16\33\26\0\5\33\3\0\30\33"+
    "\2\0\1\173\23\0\5\33\3\0\22\33\1\157\5\33"+
    "\26\0\5\33\3\0\1\174\27\33\26\0\5\33\3\0"+
    "\4\33\1\70\23\33\26\0\5\33\3\0\15\33\1\70"+
    "\12\33\26\0\5\33\3\0\7\33\1\175\20\33\26\0"+
    "\5\33\3\0\10\33\1\176\17\33\26\0\5\33\3\0"+
    "\23\33\1\177\4\33\26\0\5\33\3\0\4\33\1\200"+
    "\23\33\26\0\5\33\3\0\22\33\1\201\5\33\26\0"+
    "\5\33\3\0\23\33\1\202\4\33\26\0\5\33\3\0"+
    "\17\33\1\70\10\33\26\0\5\33\3\0\4\33\1\203"+
    "\23\33\26\0\5\33\3\0\13\33\1\146\14\33\6\0"+
    "\7\124\1\162\3\124\1\163\3\124\1\204\55\124\1\162"+
    "\3\124\1\163\3\124\1\205\46\124\7\165\1\206\3\165"+
    "\1\126\52\165\1\131\3\0\14\131\4\207\1\210\42\131"+
    "\3\0\12\131\1\211\1\131\5\167\42\131\3\0\14\131"+
    "\4\212\1\213\41\131\20\0\5\33\3\0\15\33\1\143"+
    "\12\33\26\0\5\33\3\0\12\33\1\70\15\33\55\0"+
    "\1\214\5\0\1\215\30\0\5\33\3\0\23\33\1\70"+
    "\4\33\26\0\5\33\3\0\23\33\1\216\4\33\26\0"+
    "\5\33\3\0\5\33\1\177\22\33\26\0\5\33\3\0"+
    "\27\33\1\70\26\0\5\33\3\0\3\33\1\217\24\33"+
    "\26\0\5\33\3\0\16\33\1\67\11\33\26\0\5\33"+
    "\3\0\2\33\1\220\25\33\6\0\7\205\1\221\56\205"+
    "\7\165\1\206\3\165\1\126\3\165\1\204\46\165\1\131"+
    "\3\0\12\131\1\211\1\131\5\222\41\131\51\0\1\223"+
    "\44\0\1\224\55\0\5\33\3\0\1\33\1\70\26\33"+
    "\26\0\5\33\3\0\24\33\1\160\3\33\26\0\5\33"+
    "\3\0\7\33\1\70\20\33\6\0\7\205\1\221\7\205"+
    "\1\127\46\205\46\0\1\225\70\0\1\226\46\0\1\226"+
    "\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6534];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\2\1\1\11\1\1\3\11"+
    "\32\1\3\11\1\1\2\11\1\0\1\1\1\0\1\11"+
    "\1\1\1\0\1\1\1\0\36\1\4\0\1\11\1\1"+
    "\2\0\1\1\1\0\25\1\2\0\1\1\2\0\1\1"+
    "\1\0\2\1\1\0\11\1\2\0\2\1\1\0\2\1"+
    "\2\0\3\1\1\0\1\1\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private boolean _existenTokens = true;
    public boolean _existenTokens(){
        return this._existenTokens;
    }
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoS2H(java.io.Reader in) {
  //Código que se ejecuta al inicio de la clase,
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    //Código que se ejecutará al final del proceso
    this._existenTokens = false;
    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { Tokens t = new Tokens (yyline+1,yycolumn+1,true,1,"Error 1 (Léxico):Caracter no válido ("+yytext()+") en línea: " + (yyline+1) + ", columna: " + (yycolumn+1));
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 25: break;
          case 2:
            { //Vamos a ignorar este también.
    Tokens t = new Tokens (yytext(),"Salto de Linea",yyline+1,yycolumn+1,false);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 26: break;
          case 3:
            { //Este lexema se ignora
    Tokens t = new Tokens (yytext(),"Espacio en blanco",yyline+1,yycolumn+1,false);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 27: break;
          case 4:
            { Tokens t = new Tokens (yytext(),"OP_BOOL",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 28: break;
          case 5:
            { Tokens t = new Tokens (yytext(),"CAR_ESP",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 29: break;
          case 6:
            { Tokens t = new Tokens (yytext(),"PAR_APER",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 30: break;
          case 7:
            { Tokens t = new Tokens (yytext(),"PAR_CIER",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 31: break;
          case 8:
            { Tokens t = new Tokens (yytext(),"OP_ARIT",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 32: break;
          case 9:
            { Tokens t = new Tokens (yytext(),"NUMERO ENTERO",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 33: break;
          case 10:
            { Tokens t = new Tokens (yytext(),"OP_REL",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 34: break;
          case 11:
            { Tokens t = new Tokens (yytext(),"OP_ASIG",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 35: break;
          case 12:
            { Tokens t = new Tokens (yytext(),"IDENTIFICADOR",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 36: break;
          case 13:
            { Tokens t = new Tokens (yytext(),"COR_APER",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 37: break;
          case 14:
            { Tokens t = new Tokens (yytext(),"COR_CIER",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 38: break;
          case 15:
            { Tokens t = new Tokens (yytext(),"LLAVE_APER",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 39: break;
          case 16:
            { Tokens t = new Tokens (yytext(),"LLAVE_CIER",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 40: break;
          case 17:
            { Tokens t = new Tokens (yytext(),"CADENA",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 41: break;
          case 18:
            { Tokens t = new Tokens (yytext(),"NUMERO_FLOTANTE",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 42: break;
          case 19:
            { Tokens t = new Tokens (yytext(),"COMENTARIO",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 43: break;
          case 20:
            { Tokens t = new Tokens (yyline+1,yycolumn+1,true,2,"Error 2 (Léxico): Número inválido ("+ yytext() +") en fila: " + (yyline+1) + ", columna: " + (yycolumn+1));
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 44: break;
          case 21:
            { Tokens t = new Tokens (yytext(),"PALABRA_RESERVADA",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 45: break;
          case 22:
            { Tokens t = new Tokens (yyline+1,yycolumn+1,true,3,"Error 3 (Léxico): Número flotante inválido ("+ yytext() +") en: " + (yyline+1) + ", columna: " + (yycolumn+1));
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 46: break;
          case 23:
            { Tokens t = new Tokens (yyline+1,yycolumn+1,true,3,"Error 4 (Léxico): Formato de tiempo inválido ("+ yytext() +") en: " + (yyline+1) + ", columna: " + (yycolumn+1));
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 47: break;
          case 24:
            { Tokens t = new Tokens (yytext(),"TIEMPO",yyline+1,yycolumn+1,true);
    this._existenTokens = true;
    return t;
            }
            // fall through
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
