/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizador;

import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import JFlex.Tokens;
import TablaSimbolos.TablaSimbolos;

public class Tabla_Simbolos extends javax.swing.JFrame {
    String[] columnNames = {"Lexema","Componente Léxico","Fila","Columna"};
    public Tabla_Simbolos(JFrame padre,TablaSimbolos simbolos) {
        this.setLocation(150, 150);
        initComponents();
        llenarTabla(simbolos);
    }
    public void llenarTabla(TablaSimbolos simbolos){
        DefaultTableModel modelo;
        modelo = new DefaultTableModel(columnNames,0);
        tblWords.setFillsViewportHeight(true);
        tblWords.setModel(modelo);
        for(Tokens objeto:simbolos.verTablaSimbolos()){
            modelo.addRow(objeto.tokenObject());
        }
        TableColumn col = tblWords.getColumnModel().getColumn(0);
        col.setPreferredWidth(160);
        col.setMinWidth(160);
        col.setMaxWidth(160);
        tblWords.setRowHeight(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblWords = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabla de Símbolos");

        tblWords.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tblWords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Palabra", "Parámetros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblWords);
        if (tblWords.getColumnModel().getColumnCount() > 0) {
            tblWords.getColumnModel().getColumn(0).setMinWidth(200);
            tblWords.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblWords.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblWords;
    // End of variables declaration//GEN-END:variables

}
